server:
  port: 9091

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/gwa_allservices
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secretKey: ${ssa_secretkey}
  issuer:  ${ssa_issuer}
  audience: ${ssa_audience}



